spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 2000
          service-product:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
#            request-interceptors:
#              - com.acmhuang.order.interceptor.XTokenRequestInterceptor
            retryer: feign.Retryer.Default
feign:
  sentinel:
    ## 开启之后远程调用失败则会自动走兜底方法
    enabled: true