spring:
  cloud:
    gateway:
      routes:
        - id: order-route
          ## lb代表负载均衡
          uri: lb://service-order
          ## 路径匹配
          predicates:
            - Path=/api/order/**
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**